### ISSUE TITLE
Build.gradle incorrect implementation

### ISSUE THREAD

**Issue by drewstephensdesigns** [omjoonkim/SkeletonLoadingView#3]
You currently have implementetion  'com.omjoonkim.library:skeleton-loading-view:0.1.3'

Implementation is spelt incorrectly thus causing project build to fail.  Needs to be correct to implementation

**Comment by omjoonkim** [comment]
Hi @DrewStephensCoding .I don't understand clearly. Could you please elaborate a bit more? What spelt is wrong??
